config/routes.rb
ProjetoSensores::Application.routes.draw do

  root 'application#index'
  resources :position_details

end

app/models/position_detail.rb
class PositionDetail < ActiveRecord::Base

  validates :phone_model, presence: true
  validates :carrier, presence: true
  validates :signal, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :timestamp, presence: true
  
  def with_api_params(params)
    self.phone_model = params[:phone_model]
    self.carrier = params[:carrier]
    self.signal = params[:signal]
    self.latitude = params[:latitude]
    self.longitude = params[:longitude]
    self.timestamp = params[:timestamp]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  after_filter :set_access_control_headers

  def index
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

end

app/controllers/position_details_controller.rb
class PositionDetailsController < ApplicationController
  respond_to :json, :html

  def index
    @position_details = PositionDetail.all
    respond_with(@position_details)
  end

  def create
    @position_details = PositionDetail.new
    @position_details.with_api_params(params)
    if @position_details.save
      render json: "Created with success!"
    else
      render nothing: true, status: "400"
    end
  end

  private
  def position_detail_params
    params.require(:position_details).permit(:phone_model, :carrier, :signal, :latitude, :longitude, :timestamp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_message_helper.rb
module FlashMessageHelper

  def flash_message level, content
    content_tag :p, content, class: level
  end

  def flash_messages
    [:alert, :notice, :error].map do |level|
      flash_message(level, flash[level]) if flash[level]
    end.join.html_safe
  end

end

app/helpers/position_details_helper.rb
module PositionDetailsHelper
end

app/views/application/index.html.erb
<style>
    html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
    }

    #panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
    }
</style>

</head>


<div id="panel">
  <button onclick="toggleHeatmap()">Toggle Heatmap</button>
  <button onclick="changeGradient()">Change gradient</button>
  <button onclick="changeRadius()">Change radius</button>
  <button onclick="changeOpacity()">Change opacity</button>
</div>

<br>
<br>
<br>
<br>
<div id="map-canvas">
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=visualization"></script>
<script>
    // Adding 500 Data Points
    var map, pointarray, heatmap;

    var taxiData = [
        new google.maps.LatLng(37.782551, -122.445368),
        new google.maps.LatLng(37.782745, -122.444586),
        new google.maps.LatLng(37.782842, -122.443688),
        new google.maps.LatLng(37.782919, -122.442815),
        new google.maps.LatLng(37.782992, -122.442112),
        new google.maps.LatLng(37.783100, -122.441461),
        new google.maps.LatLng(37.783206, -122.440829),
        new google.maps.LatLng(37.783273, -122.440324),
        new google.maps.LatLng(37.783316, -122.440023)
    ];

    function initialize() {
        var mapOptions = {
            zoom: 13,
            center: new google.maps.LatLng(37.774546, -122.433523),
            mapTypeId: google.maps.MapTypeId.SATELLITE
        };

        var mapa = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        var pointArray = new google.maps.MVCArray(taxiData);

        heatmap = new google.maps.visualization.HeatmapLayer({data: pointArray});

        heatmap.setMap(mapa);
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Projeto Sensores</title>
  <%= stylesheet_link_tag "application", "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="">
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Projeto Sensores", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Listar Posições", position_details_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <br/>
  <br/>
  <%= flash_messages %>
  <%= yield %>
</div>
<!-- /.container -->
</body>
</html>

app/views/position_details/index.html.erb
<h2>Posições Cadastradas:</h2>

<% unless @position_details.empty? %>

    <table class="table">
      <tr>
        <th>Modelo do Telefone</th>
        <th>Operadora</th>
        <th>Potência do Sinal</th>
        <th>Latitute</th>
        <th>Longitute</th>
        <th>Timestamp</th>
      </tr>
      <% @position_details.each do |position| %>
          <tr>
            <td><%= position.phone_model %></td>
            <td><%= position.carrier %></td>
            <td><%= position.signal %></td>
            <td><%= position.latitude %></td>
            <td><%= position.longitude %></td>
            <td><%= position.timestamp %></td>
          </tr>
      <% end %>

<% else %>
    <h3>Nenhuma posição cadastrada até o momento! :(</h3>
<% end %>
</table>